apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  PROCS: "1"
  ADDRESS_SUFFIX: default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-go
  labels:
    app.kubernetes.io/instance: a
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: a
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: a
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: a
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-go
  labels:
    app.kubernetes.io/instance: b
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: b
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: b
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: b
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-go
  labels:
    app.kubernetes.io/instance: c
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: c
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: c
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: c
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-go
  labels:
    app.kubernetes.io/instance: d
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: d
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: d
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: d
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-go
  labels:
    app.kubernetes.io/instance: e
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: e
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: e
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: e
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-go
  labels:
    app.kubernetes.io/instance: f
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: f
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: f
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: f
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-go
  labels:
    app.kubernetes.io/instance: g
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: go
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: g
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: gs
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: go
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-go
        name: g
      restartPolicy: Always
