apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: rc
data:
  PROCS: "1"
  DEFAULT_HOST: "g"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: a
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: a
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: a
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: a
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: b
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: b
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: b
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: b
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: c
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: c
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: c
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: c
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: d
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: d
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: d
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - env:
        - name: PROCS
          value: "1"
        image: davidbetz/recursivecall-js:2020-02
        name: d
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: e
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: e
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: e
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: e
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: f
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: f
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: f
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: f
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-js
  namespace: rc
  labels:
    app.kubernetes.io/instance: g
    app.kubernetes.io/name: recursivecall
    app.kubernetes.io/version: js
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: g
      app.kubernetes.io/name: recursivecall
      app.kubernetes.io/version: js
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: g
        app.kubernetes.io/name: recursivecall
        app.kubernetes.io/version: js
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-config
        image: davidbetz/recursivecall-js:2020-02
        name: g
      restartPolicy: Always
