apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
  namespace: rc
spec:
  routes:
  - match: PathPrefix(`/g`) || PathPrefix(`/`)
    kind: Rule
    services:
    - name: g
      port: 3000
  - match: PathPrefix(`/c`)
    kind: Rule
    services:
    - name: c
      port: 3000
  - match: PathPrefix(`/a`)
    kind: Rule
    services:
    - name: a
      port: 3000
