apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: rc
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: g
          servicePort: 3000
      - path: /g
        backend:
          serviceName: g
          servicePort: 3000
      - path: /c
        backend:
          serviceName: c
          servicePort: 3000
      - path: /a
        backend:
          serviceName: a
          servicePort: 3000
